// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GmailClientService is a Wails3 service for Gmail API operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * CompleteAuth completes the authentication process with the provided code
 */
export function CompleteAuth(authCode: string): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3077179117, authCode) as any;
    return $resultPromise;
}

/**
 * GetAuthURL returns the URL for OAuth authentication
 */
export function GetAuthURL(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2184861687) as any;
    return $resultPromise;
}

/**
 * GetLabels retrieves Gmail labels for the authenticated user
 */
export function GetLabels(): Promise<string[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1898797023) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType0($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

/**
 * IsAuthenticated checks if the user is authenticated
 */
export function IsAuthenticated(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1717613591) as any;
    return $resultPromise;
}

/**
 * Logout logs the user out by clearing the token and resetting the service
 */
export function Logout(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(4015480642) as any;
    return $resultPromise;
}

/**
 * OpenAuthURL opens the authentication URL in the default browser
 */
export function OpenAuthURL(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1496664787) as any;
    return $resultPromise;
}

/**
 * OpenBrowser opens a browser to the specified URL
 */
export function OpenBrowser(url: string): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2860928708, url) as any;
    return $resultPromise;
}

/**
 * RegenerateAuthURL regenerates the authentication URL
 */
export function RegenerateAuthURL(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(76616033) as any;
    return $resultPromise;
}

/**
 * ServiceName returns the name of the service
 */
export function ServiceName(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1578136908) as any;
    return $resultPromise;
}

/**
 * ServiceShutdown cleans up resources
 */
export function ServiceShutdown(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2318530965) as any;
    return $resultPromise;
}

/**
 * ServiceStartup initializes the Gmail client service
 */
export function ServiceStartup(options: application$0.ServiceOptions): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(46770752, options) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
